### ISSUE TITLE
Crashes when trying to connect

### ISSUE THREAD

**Issue by kevinpostal** [DanielOaks/oragono#66]
The Server Crashes the moment I try connecting.

```
2016/11/04 01:46:51 oragono.test listening on :6667 using plaintext.
2016/11/04 01:46:51 oragono.test listening on 127.0.0.1:6668 using plaintext.
2016/11/04 01:46:51 oragono.test listening on [::1]:6668 using plaintext.
2016/11/04 01:46:51 oragono.test listening on :6697 using TLS.
2016/11/04 01:46:51 Oragono v0.5.0-unreleased running
2016/11/04 01:46:51 oragono.test websocket listening on :8080 using plaintext.
panic: runtime error: index out of range

goroutine 15 [running]:
panic(0x7a3560, 0xc4200100b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/DanielOaks/go-ident.Query(0xc42039f6c0, 0xe, 0x1a0b, 0xe3ee, 0x4020000000000000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/kevin/oragono-master/src/github.com/DanielOaks/go-ident/client.go:101 +0x6af
github.com/DanielOaks/oragono/irc.NewClient(0xc420091b00, 0x9b5bc0, 0xc420026070, 0x0, 0x0)
	/home/kevin/oragono-master/src/github.com/DanielOaks/oragono/irc/client.go:110 +0x607
created by github.com/DanielOaks/oragono/irc.(*Server).Run
	/home/kevin/oragono-master/src/github.com/DanielOaks/oragono/irc/server.go:349 +0x51b
exit status 2
```

**Comment by DanielOaks** [comment]
Ah, I made a mistake when parsing the `IDENT` response.

This commit fixes it: https://github.com/DanielOaks/go-ident/commit/18356197d025d73b13426933c029fc48cc906df4

You should be able to pull the latest version of go-ident with:
```
go get -u github.com/DanielOaks/go-ident
```

Thanks for giving it a shot though! Let me know if you run into any other issues and I'll be glad to help.

**Comment by kevinpostal** [comment]
That fixed the crashing. I noticed tho on some irc clients, I can't seem to connect to the server.

It hangs with the message `21:07 *** Looking up your username`

Freezes with http://limechat.net/mac/

yet https://www.irccloud.com/ can connect.

**Comment by DanielOaks** [comment]
Hmm, the ident lookup should timeout after eight seconds... That is still a fairly long time to wait though.

Are you able to connect after eight seconds, or does it just not connect at all?

**Comment by DanielOaks** [comment]
Actually, I just realised that while I timeout reading responses, I didn't timeout actually writing the info (see also https://github.com/DanielOaks/go-ident/commit/3675b87fe48868ce2dfaa162d46de64794db2b61 ).

Mind updating go-ident again and giving it another shot? If it now works after the eight seconds I'll make sure I time that out sooner, and probably make it configurable.

**Comment by DanielOaks** [comment]
Aight so this should be all fixed up, but if you do run into this issue feel free to re-open or create a new one. Thanks again for the report, it's much appreciated!
