### ISSUE TITLE
Make the project `go get`-able

### ISSUE THREAD

**Issue by jamesog** [DanielOaks/oragono#79]
Currently you can't `go get` this repo because both `oragono.go` and `oragono-web.go` declare `function main()`.

You should move these to their own directories, e.g. `cmd/oragono/oragono.go` and `cmd/oragono-web/oragono-web.go`.

The `go` tool expects that one directory is one package. Although both of these files are `package main` they are really different things and so should be separated.

**Comment by DanielOaks** [comment]
Ah, thanks for the issue! I'll move -web to its own directory along those lines and see what I wanna do regarding the base oragono.go. Thanks very much for bringing up this issue, I agree and I'll make sure it gets resolved :)

**Comment by DanielOaks** [comment]
It's a bit ugly but 34089bd383d5178c7f4ce842b5b3ed86629b0bcb resolves this issue at least (and makes the project go get'able). I'll take a look at some further packaging docs/recommendations and will probably end up moving the core `oragono.go` file to its own directory in a similar way – thanks for letting me know about this!

**Comment by jamesog** [comment]
Thanks!
