### ISSUE TITLE
Build failures :/

### ISSUE THREAD

**Issue by prologic** [DanielOaks/oragono#80]
I'd love to be able to test this out and contribute in some way but sadly the build fails so (for now) I've given up further investigations :/

```#!bash
~/tmp/oragono
 (master) 0
$ go build oragono.go
# github.com/DanielOaks/oragono/irc
../../go/src/github.com/DanielOaks/oragono/irc/strings.go:21: precis.Nickname.CompareKey undefined (type *precis.Profile has no field or method CompareKey)
../../go/src/github.com/DanielOaks/oragono/irc/strings.go:21: not enough arguments to return
../../go/src/github.com/DanielOaks/oragono/irc/strings.go:26: precis.Nickname.CompareKey undefined (type *precis.Profile has no field or method CompareKey)
../../go/src/github.com/DanielOaks/oragono/irc/strings.go:50: precis.Nickname.CompareKey undefined (type *precis.Profile has no field or method CompareKey)
```

**Comment by DanielOaks** [comment]
Hey prologic. Sorry for this issue, Oragono actually makes use of a newly-introduced CompareKey function. For more info, there's this issue on the core Go repo: https://github.com/golang/go/issues/17386

Is there any chance I could ask you to cd to the Oragono directory and run this command or something similar, to update the required [`precis` package](https://godoc.org/golang.org/x/text/secure/precis)?
`go get ./...`

Hopefully this should resolve the build issue for you, but if it doesn't please feel free to let me know! :)

**Comment by prologic** [comment]
I actually already ran `go get ./...` :)

Does this build on Go 1.7.4?

**Comment by DanielOaks** [comment]
Hmm that's weird, I'm using 1.7.3 here. I'll throw this into a new VM, make sure it compiles from scratch (and that I haven't messed with any of my source files).

**Comment by prologic** [comment]
It's probably also worthwhile [vendoring](https://blog.gopheracademy.com/advent-2015/vendor-folder/) your package too so upstream bugs or changing code don't break builds until you've tested and updated to newer versions. I've had success with [vendetta](https://github.com/dpw/vendetta) for managing my vendor'd packages.

**Comment by DanielOaks** [comment]
Weird, from a plain `go get` this seems to work alright. Mind running this command and seeing whether it helps?
```
go get -u golang.org/x/text/secure/precis
```

I'll definitely take a look at vendoring. #52 threw me something similar but I was a bit offput at first. I'll need to take a better look at Go packaging (specifically vendoring), see what I can do there. Thanks very much for the link, should be helpful!

**Comment by prologic** [comment]
Okay I have a build working!

**Comment by DanielOaks** [comment]
Awesome, thanks for the issue and I'm glad to hear that! I'll investigate app packaging though, check out vendored packages and all.
