### ISSUE TITLE
USERHOST is needed

### ISSUE THREAD

**Issue by vegax87** [DanielOaks/oragono#90]
Many IRC clients automatically perform the USERHOST command right after the MOTD for various reasons

        302     RPL_USERHOST
                        ":[<reply>{<space><reply>}]"

                - Reply format used by USERHOST to list replies to
                  the query list.  The reply string is composed as
                  follows:

                  <reply> ::= <nick>['*'] '=' <'+'|'-'><hostname>

                  The '*' indicates whether the client has registered
                  as an Operator.  The '-' or '+' characters represent
                  whether the client has set an AWAY message or not
                  respectively.

**NOTE**: - means the client is marked as away, while + is online

**Comment by DanielOaks** [comment]
This is now in latest git, thanks!
