### ISSUE TITLE
Timestamp issue?

### ISSUE THREAD

**Issue by martinlindhe** [DanielOaks/oragono#94]
Trying out the irc server, everything's working well.

But I see some issue where local time vs irc server time seems to be inconsistent

With mIRC (Windows) and Mutter (iOS) clients, when something is broadcast from the irc server to the clients, the time are +1 hour.
With LimeChat (OSX), I don't see this issue. Possibly because LimeChat only cares of arrival time of messages.

I suspect this is a irc server configuration issue, possibly related to the "server-time" capability.

**Comment by DanielOaks** [comment]
Hey @martinlindhe!

Hmm, that's very interesting indeed. Just so we can eliminate things, could you please double-check the time on the machine Oragono's running on? Including time, timezone, DST settings, making sure it's synced with NTP and all that fun stuff.

The server grabs the time right now just before it sends it out, [here](https://github.com/DanielOaks/oragono/blob/master/irc/client.go#L552). I'd be very interested to work out what's going on here. Perhaps either a DST issue or something related.

So I have some more info and can try to repro here, what's the time/region for the server, and for the clients connecting to it? Both synced with NTP?

Likely, what's going on is the server's outputting an 'unexpected' timestamp with server-time, clients don't expect it so the time looks all weird, yeah.

**Comment by martinlindhe** [comment]
Okay, server time is synced using NTP, timezone is Europe/Stockholm (UTC+1, Central European time). The system does obey DST.

The clients are all using NTP too

In this little screenshot, we see some events, all times are 1 hour forward.
the "<win> hj" line has the correct time according to wall time, and is entered in the client on the screenshot (mirc).
At the time of screenshoting, the wall time was 23:46, and in UTC the time was 22:46.

Server time is configured as such:
```
git@battle:~$ timedatectl status
      Local time: mon 2017-02-06 23:47:39 CET
  Universal time: mon 2017-02-06 22:47:39 UTC
        RTC time: mon 2017-02-06 22:47:39
       Time zone: Europe/Stockholm (CET, +0100)
```

![capture](https://cloud.githubusercontent.com/assets/181531/22669823/afb6e310-ecc6-11e6-8a8b-aaed0b7bb14f.PNG)

**Comment by martinlindhe** [comment]
PS, can one disable the server capabilities easily, I want to test to disable the server-time.
I tried to put the following in the ircd.yaml without success
```
server:
    capabilities:
        - "-server-time"
```

**Comment by DanielOaks** [comment]
That's strange. Given the server timezone is UTC+1 I wonder whether it could be outputting it in something rather than GMT or some other similar issues around there. I'll play with this as well, thanks for letting me know.

Right now there's no way to disable specific caps yeah, except rebuilding and removing / commenting out the appropriate code. I'll see what's up here though.

**Comment by martinlindhe** [comment]
I figured it out, the fix is at https://github.com/DanielOaks/oragono/blob/master/irc/client.go#L552

do time.Now().UTC() to get time as UTC. Solves my issue. Patch incoming...
