### ISSUE TITLE
URGENT: Server gives @ to everyone when joining an unregistered channel

### ISSUE THREAD

**Issue by vegax87** [DanielOaks/oragono#99]
Apparently the server doesn't recognize anymore who is the first user on the channel and gives @ to everyone.
I haven't tested with a registered channel yet.

Screenshot: http://imgur.com/a/KRaF4

**Comment by DanielOaks** [comment]
Yeah I stuffed this up while writing the channel registration code. I've pushed a fix to master, just performing some final tests and I'll push out a new build, thanks.

**Comment by DanielOaks** [comment]
This is fixed in the new release [here](https://github.com/DanielOaks/oragono/releases), thanks very much for the yell on this!
